### ISSUE TITLE
drush dl tweet_feed--7.x-3.x-dev gives error (must be installed manually or via UI)

### ISSUE THREAD

**Issue by knowledges33ker** [ElusiveMind/tweet_feed#6]
[~/public_html/sites/all/modules/contrib]# drush dl tweet_feed-7.x-3.x-dev
File tweet_feed-7.x-3.x-dev.tar.gz_date=1433757480 is corrupt (wrong [error]
md5 checksum).

**Comment by ElusiveMind** [comment]
Wow. I've not seen THIS before. Maybe posting an update will fix that. I've not try to install this way but I will test and report back on my experience.

**Comment by ElusiveMind** [comment]
Looks like you may need to wait a few hours to do this after dev builds are pushed

https://www.drupal.org/node/1961304#comment-7885369

**Comment by knowledges33ker** [comment]
Yes, after a few hours it resolves
