### ISSUE TITLE
installing tweet_feed-7.x-3.x-dev gives warning message on screen

### ISSUE THREAD

**Issue by knowledges33ker** [ElusiveMind/tweet_feed#7]
Warning: mkdir() [function.mkdir]: File exists in DrupalLocalStreamWrapper->mkdir() (line 639 of /home/sandbx/public_html/includes/stream_wrappers.inc).

**Comment by ElusiveMind** [comment]
This is in the latest build on Drupal.org (dev build).

**Comment by ElusiveMind** [comment]
Please provide feedback when checked.

**Comment by knowledges33ker** [comment]
This is fixed. New install went smoothly.
